# Generated by Django 6.0.4 on 2026-05-15 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='doacoes/'),
        ),
    ]
