# Generated by Django 6.0.4 on 2026-05-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usuario_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao',
            name='categoria',
            field=models.CharField(choices=[('Padaria', 'Padaria'), ('Frutas', 'Frutas'), ('Refeições', 'Refeições'), ('Doces', 'Doces'), ('Laticínios', 'Laticínios'), ('Outros', 'Outros')], default='Outros', max_length=20),
        ),
    ]
