# Generated by Django 6.0.4 on 2026-05-26 14:41

import api.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_doacao_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('alerta', 'Alerta'), ('ranking', 'Ranking'), ('impacto', 'Impacto'), ('mensagem', 'Mensagem')], default='alerta', max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='doacao',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='doacao',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doacao',
            name='descricao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='doacao',
            name='receptor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='api.usuario'),
        ),
        migrations.AddField(
            model_name='doacao',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('reservado', 'Reservado'), ('entregue', 'Entregue')], db_index=True, default='disponivel', max_length=15),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='validade',
            field=models.DateField(validators=[api.models.validate_validade_futura]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AddIndex(
            model_name='doacao',
            index=models.Index(fields=['status', 'validade'], name='api_doacao_status_82e1a2_idx'),
        ),
        migrations.AddIndex(
            model_name='doacao',
            index=models.Index(fields=['categoria', 'status'], name='api_doacao_categor_bbb02e_idx'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='api.usuario'),
        ),
    ]
